baseURL = "http://SegFault42.com"
languageCode = "en-us"
title = "SegFault42"
theme = "code-editor"

[params.social]
    twitter = "SegFault_42"
    keybase = "SegFault42"
    github = "SegFault42"

[[menu.main]]
    name = "Index"
    identifier = "index"
    weight = 1
    url = "/posts"

## Site Settings
[params]
    author = "SegFault42"
    title = "Title"
    # description = "..."
    #authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
	highlightjs = true
    highlightjsstyle = "dark"
    # please choose either GraphComment or Disqus
    #GraphCommentId = "..."
    
    # Table of contents
    #toc = none, "hugo", or "tocbot"
